apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    version: 1.0.0
  annotations:
    PodDescription: ini adalah contoh pod yang menggunakan annotation
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
